### ISSUE TITLE
Auto-scaler test never runs on kubecf

### ISSUE THREAD

**Issue by mook-as** [SUSE/brain-tests-release#10]
Currently the [autoscaler test](https://github.com/SUSE/brain-tests-release/blob/master/src/acceptance-tests-brain/test-scripts/018_autoscaler_test.rb) looks for the following statefulsets:

- [autoscaler-api](https://github.com/SUSE/brain-tests-release/blob/73e7deaa2f4c52ca5bf10b05a7bda70a783a38d0/src/acceptance-tests-brain/test-scripts/018_autoscaler_test.rb#L12)
- [autoscaler-actors](https://github.com/SUSE/brain-tests-release/blob/73e7deaa2f4c52ca5bf10b05a7bda70a783a38d0/src/acceptance-tests-brain/test-scripts/018_autoscaler_test.rb#L13)
- [autoscaler-metrics](https://github.com/SUSE/brain-tests-release/blob/73e7deaa2f4c52ca5bf10b05a7bda70a783a38d0/src/acceptance-tests-brain/test-scripts/018_autoscaler_test.rb#L14)
- [autoscaler-postgres](https://github.com/SUSE/brain-tests-release/blob/73e7deaa2f4c52ca5bf10b05a7bda70a783a38d0/src/acceptance-tests-brain/test-scripts/018_autoscaler_test.rb#L15)

However, kubecf has the following statefulsets:

- [asapi](https://github.com/cloudfoundry-incubator/kubecf/blob/21802f2d53457fa67e185e86349ab1a8ccfc0668/deploy/helm/kubecf/assets/operations/instance_groups/app-autoscaler.yaml#L383)
- [asactors](https://github.com/cloudfoundry-incubator/kubecf/blob/21802f2d53457fa67e185e86349ab1a8ccfc0668/deploy/helm/kubecf/assets/operations/instance_groups/app-autoscaler.yaml#L130)
- [asmetrics](https://github.com/cloudfoundry-incubator/kubecf/blob/21802f2d53457fa67e185e86349ab1a8ccfc0668/deploy/helm/kubecf/assets/operations/instance_groups/app-autoscaler.yaml#L244)
- [asdatabase](https://github.com/cloudfoundry-incubator/kubecf/blob/21802f2d53457fa67e185e86349ab1a8ccfc0668/deploy/helm/kubecf/assets/operations/instance_groups/app-autoscaler.yaml#L99)
- [asnozzle](https://github.com/cloudfoundry-incubator/kubecf/blob/21802f2d53457fa67e185e86349ab1a8ccfc0668/deploy/helm/kubecf/assets/operations/instance_groups/app-autoscaler.yaml#L336)

This means the tests will never run.  I believe the existing names are correct for SCF, which will never use this BOSH release (it uses the one in-tree instead).

**Comment by f0rmiga** [comment]
We should enable/disable the tests using a BOSH property. On KubeCF, we conditionally render that property if the feature flag is enabled.
